# Generated by Django 2.0.6 on 2018-07-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inconsistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'Public'), ('2', 'Private')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sugestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100)),
                ('inconsistency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='rule.Inconsistency')),
            ],
            options={
                'ordering': ('inconsistency',),
            },
        ),
    ]
