# Generated by Django 2.0.6 on 2018-07-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sugestion',
            new_name='Suggestion',
        ),
    ]
