# Generated by Django 2.0.6 on 2018-07-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20180708_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={},
        ),
    ]
