# Generated by Django 2.0.6 on 2018-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_inconsistency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inconsistency',
            name='isRegex',
            field=models.BooleanField(default=False),
        ),
    ]
