# Generated by Django 2.0.6 on 2018-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0005_inconsistency_isregex'),
    ]

    operations = [
        migrations.AddField(
            model_name='inconsistency',
            name='regexType',
            field=models.IntegerField(choices=[('1', 'regex'), ('2', 'regexBoundary'), ('3', 'regexText')], default=3),
        ),
        migrations.AlterField(
            model_name='inconsistency',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inconsistency',
            name='pattern',
            field=models.CharField(max_length=100),
        ),
    ]
