# Generated by Django 2.0.6 on 2018-09-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0006_auto_20180820_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inconsistency',
            name='regexType',
            field=models.IntegerField(choices=[(1, 'regex'), (2, 'regexBoundary'), (3, 'regexText')], default=3),
        ),
        migrations.AlterField(
            model_name='inconsistency',
            name='type',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1),
        ),
    ]
