# Generated by Django 2.0.6 on 2018-08-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0005_inconsistency_isregex'),
        ('historyChangesText', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeInText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldText', models.CharField(max_length=1000)),
                ('newText', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='historychangestext',
            name='idInconsistency',
        ),
        migrations.RemoveField(
            model_name='historychangestext',
            name='idSuggestion',
        ),
        migrations.RemoveField(
            model_name='historychangestext',
            name='newText',
        ),
        migrations.RemoveField(
            model_name='historychangestext',
            name='oldText',
        ),
        migrations.AddField(
            model_name='changeintext',
            name='historyChangesText',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyChangesText', to='historyChangesText.HistoryChangesText'),
        ),
        migrations.AddField(
            model_name='changeintext',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historySuggestion', to='rule.Suggestion'),
        ),
    ]
