# Generated by Django 2.0.6 on 2018-08-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historyChangesText', '0003_auto_20180815_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeintext',
            name='historyChangesText',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changesInText', to='historyChangesText.HistoryChangesText'),
        ),
    ]
