# Generated by Django 2.0.6 on 2018-08-23 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historyChangesText', '0004_auto_20180815_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('historyChangesText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyChangesText', to='historyChangesText.HistoryChangesText')),
                ('onwerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onwerUser', to=settings.AUTH_USER_MODEL)),
                ('sharedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
