# Generated by Django 2.0.6 on 2018-08-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyChangesText', '0005_sharedtexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtexts',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
