# Generated by Django 2.0.6 on 2018-09-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historyChangesText', '0006_sharedtexts_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundInconsistencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundInconsistenciesNumber', models.IntegerField(default=0)),
                ('appliedSuggestionsNumber', models.IntegerField(default=0)),
                ('revisionNumber', models.IntegerField(default=1)),
                ('historyChangesText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundInconsistencies', to='historyChangesText.HistoryChangesText')),
            ],
        ),
        migrations.RemoveField(
            model_name='changeintext',
            name='historyChangesText',
        ),
        migrations.AddField(
            model_name='changeintext',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='changeintext',
            name='foundInconsistencies',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='changesInText', to='historyChangesText.FoundInconsistencies'),
            preserve_default=False,
        ),
    ]
