# Generated by Django 2.0.6 on 2018-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyChangesText', '0007_auto_20180919_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundinconsistencies',
            name='foundRulesNumber',
            field=models.IntegerField(default=0),
        ),
    ]
